/**
 * End-to-end check against the real generated dataset.
 *
 * The unit tests prove the maths in isolation; this proves the pipeline output
 * actually feeds it. It reads public/data directly, so a change to the
 * extraction that breaks the engine's assumptions fails here rather than
 * showing up as a wrong number in the UI.
 */

import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

import { describe, expect, it } from 'vitest';

import { type DataUnit, toTarget, toWeapon } from './adapt';
import { resolveAttack } from './resolve';

const DATA_DIR = join(process.cwd(), 'public', 'data');
const marinesPath = join(DATA_DIR, 'adeptus-astartes-space-marines.json');

// The dataset is generated by `npm run data` and not committed, so skip rather
// than fail on a fresh clone that has not built it yet.
const hasData = existsSync(marinesPath);
const describeWithData = hasData ? describe : describe.skip;

function loadUnits(file: string): DataUnit[] {
  return JSON.parse(readFileSync(join(DATA_DIR, file), 'utf8')).units;
}

describeWithData('real datasheets', () => {
  const marines = loadUnits('adeptus-astartes-space-marines.json');
  const find = (name: string) => {
    const unit = marines.find((u) => u.name === name);
    if (!unit) throw new Error(`missing unit: ${name}`);
    return unit;
  };

  it('resolves bolt rifles into terminators with a believable number', () => {
    const intercessors = find('Intercessor Squad');
    const boltRifle = intercessors.weapons.find((w) => w.name === 'Bolt Rifle');
    expect(boltRifle).toBeDefined();

    const weapon = toWeapon(boltRifle!)!;
    expect(weapon.strength).toBe(4);
    expect(weapon.ap).toBe(1);
    expect(weapon.skill).toBe(3);

    const target = toTarget(find('Terminator Squad'))!;
    const result = resolveAttack(weapon, target, { attackingModels: 5 })!;

    // 10 shots, hitting on 3+, wounding T5 on 5+, against a 2+ save that AP-1
    // only drags to 3+. This should chip a terminator squad, not delete it.
    expect(result.totalDamage).toBeGreaterThan(0);
    expect(result.totalDamage).toBeLessThan(2);
    expect(result.fractionDestroyed).toBeLessThan(0.5);
    expect(result.probabilityDestroyed).toBeLessThan(0.01);
  });

  it('rates an anti-tank weapon higher into a vehicle than a bolt rifle', () => {
    const rhino = toTarget(find('Rhino'))!;
    expect(rhino.toughness).toBe(9);
    expect(rhino.wounds).toBe(10);

    const boltRifle = toWeapon(
      find('Intercessor Squad').weapons.find((w) => w.name === 'Bolt Rifle')!
    )!;
    const meltaUnit = find('Eradicator Squad');
    const melta = meltaUnit.weapons.find((w) => /melta rifle/i.test(w.name));
    expect(melta).toBeDefined();

    const boltResult = resolveAttack(boltRifle, rhino, { attackingModels: 3 })!;
    const meltaResult = resolveAttack(toWeapon(melta!)!, rhino, { attackingModels: 3 })!;

    expect(meltaResult.totalDamage).toBeGreaterThan(boltResult.totalDamage);
  });

  it('reads Feel No Pain that BSData stores as a link name modifier', () => {
    // The value is not in the rule text -- BSData links the generic Feel No
    // Pain rule and appends "5+" to the link's name via a modifier. Reading
    // only the text finds the definition and no number, which silently left
    // 134 units without their Feel No Pain.
    const necrons = loadUnits('necrons.json');
    const nightbringer = necrons.find((u) => u.name === "C'tan Shard of the Nightbringer")!;

    expect(nightbringer.abilities.some((a) => /feel no pain 5\+/i.test(a.name))).toBe(true);

    const target = toTarget(nightbringer)!;
    expect(target.feelNoPain).toBe(5);
    expect(target.damageReduction).toBe(1); // Necrodermis
    expect(target.invulnerable).toBe(4);
  });

  it('keeps core weapon-keyword glossary out of unit abilities', () => {
    // BSData links the rule text for every weapon keyword a unit carries.
    // Those are definitions, not abilities -- a Plague Marine does not "have
    // Torrent", one of its weapons does.
    const marines = loadUnits('adeptus-astartes-space-marines.json');
    const noise = marines.filter((u) =>
      u.abilities.some((a) => /^(torrent|blast|rapid fire|anti|pistol|heavy)$/i.test(a.name))
    );
    expect(noise.map((u) => u.name)).toEqual([]);
  });

  it('keeps detachment rules off individual datasheets', () => {
    // Detachment rules apply because of the detachment you picked, not
    // because of the unit, so attaching them to every datasheet would be
    // wrong in the same way as attaching Enhancements.
    const necrons = loadUnits('necrons.json');
    const withDetachmentRules = necrons.filter((u) =>
      u.abilities.some((a) => /^(command protocols|power matrix|hyperphasing)$/i.test(a.name))
    );
    expect(withDetachmentRules.map((u) => u.name)).toEqual([]);
  });

  it('finds an invulnerable save written only in prose', () => {
    // Around 78 units have no InSv characteristic but describe the save in
    // their rules text; without the fallback they read as having none.
    const deathwatch = loadUnits('adeptus-astartes-deathwatch.json');
    const terminators = deathwatch.find((u) => u.name === 'Deathwatch Terminator Squad');
    if (!terminators) return;
    expect(toTarget(terminators)!.invulnerable).toBe(4);
  });

  it('models most of the roster without hitting unparseable characteristics', () => {
    let resolvable = 0;
    let total = 0;

    for (const unit of marines) {
      const target = toTarget(unit);
      if (target) resolvable += 1;
      total += 1;
    }

    // Some entries genuinely lack a statline; the bulk should convert.
    expect(resolvable / total).toBeGreaterThan(0.9);
  });
});
